services:
  mongodb:
    image: mongo:7
    container_name: greencare-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - greencare_mongo_data:/data/db

volumes:
  greencare_mongo_data:
