import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

export const generateProfessionalPDF = ({
  title,
  period,
  columns,
  rows,
  preparedBy = 'Admin',
  preparedPosition = 'System Administrator',
  signedBy = '',
  signedPosition = 'Manager',
  filename = 'report.pdf',
  logoImg = null,
}) => {
  const doc = new jsPDF('landscape');
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;

  const drawHeader = (data) => {
    let y = 15;
    
    // Logo / Brand (Left)
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.setTextColor(16, 185, 129); // Green-500
    
    if (logoImg) {
      doc.addImage(logoImg, 'PNG', 15, 6, 36, 11);
    } else {
      doc.text('GreenCare', 15, y);
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text('Eco-Friendly Solutions', 15, y + 5);
    }

    // Report Title (Center)
    doc.setFontSize(18);
    doc.setTextColor(20, 50, 120); // Dark Blue
    doc.text('GreenCare', pageWidth / 2, y, { align: 'center' });
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text(title, pageWidth / 2, y + 7, { align: 'center' });

    // Report Period (Right)
    doc.setFontSize(10);
    doc.setTextColor(20, 50, 120);
    doc.text('REPORT PERIOD', pageWidth - 15, y, { align: 'right' });
    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'bold');
    doc.text(period, pageWidth - 15, y + 5, { align: 'right' });

    // Blue Line Divider
    y += 12;
    doc.setDrawColor(20, 50, 120);
    doc.setLineWidth(0.5);
    doc.line(15, y, pageWidth - 15, y);

    // Period Text above table
    y += 8;
    doc.setFontSize(11);
    doc.text(`Period: ${period}`, 15, y);
  };

  const drawFooter = (data) => {
    const pageNumber = doc.internal.getCurrentPageInfo().pageNumber;
    const generatedOn = format(new Date(), 'yyyy-MM-dd HH:mm:ss');
    const generatedBy = 'admin@greencare.rw';

    // Footer divider
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.5);
    doc.line(15, pageHeight - 15, pageWidth - 15, pageHeight - 15);

    // Footer text
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(80, 80, 80);
    const footerText = `Generated on: ${generatedOn}   |   Generated by: ${generatedBy}   |   © ${new Date().getFullYear()} GreenCare. All rights reserved.`;
    doc.text(footerText, pageWidth / 2, pageHeight - 10, { align: 'center' });
    
    // Page number
    doc.text(`Page ${pageNumber}`, pageWidth - 15, pageHeight - 10, { align: 'right' });
  };

  // Generate Table
  autoTable(doc, {
    head: [columns],
    body: rows,
    startY: 40,
    theme: 'striped',
    headStyles: {
      fillColor: [20, 50, 120], // Dark Blue matching reference
      textColor: 255,
      fontStyle: 'bold',
      halign: 'center',
      valign: 'middle',
    },
    bodyStyles: {
      halign: 'center',
      valign: 'middle',
      fontSize: 9,
    },
    // Style the first column (#) as a narrow, muted index column
    columnStyles: {
      0: {
        halign: 'center',
        cellWidth: 12,
        fillColor: [240, 244, 255],
        textColor: [80, 100, 160],
        fontStyle: 'bold',
        fontSize: 8,
      },
    },
    alternateRowStyles: {
      fillColor: [248, 249, 250],
    },
    margin: { top: 40, bottom: 45, left: 15, right: 15 },
    didDrawPage: (data) => {
      drawHeader(data);
      drawFooter(data);
    },
  });

  // Calculate position for signatures
  let finalY = doc.lastAutoTable.finalY + 15;
  
  // If not enough space for signatures, add new page
  if (finalY + 40 > pageHeight - 20) {
    doc.addPage();
    finalY = 40;
  }

  // Draw Signature Boxes
  const boxWidth = (pageWidth - 40) / 2;
  const boxHeight = 45; // Increased height to prevent overlapping
  const leftX = 15;
  const rightX = pageWidth / 2 + 5;

  // Left Box - Prepared By
  doc.setDrawColor(200, 210, 230); // Light blue border
  doc.setLineWidth(0.5);
  doc.setFillColor(252, 253, 255);
  doc.rect(leftX, finalY, boxWidth, boxHeight, 'FD');
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(20, 50, 120);
  doc.text('PREPARED BY', leftX + 5, finalY + 7);
  
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.text('Name', leftX + 5, finalY + 15);
  doc.text(':', leftX + 25, finalY + 15);
  doc.text(preparedBy, leftX + 30, finalY + 15);
  
  doc.text('Position', leftX + 5, finalY + 22);
  doc.text(':', leftX + 25, finalY + 22);
  doc.text(preparedPosition, leftX + 30, finalY + 22);
  
  doc.text('Signature', leftX + 5, finalY + 29);
  doc.text(':', leftX + 25, finalY + 29);
  doc.setDrawColor(180, 180, 180);
  doc.line(leftX + 30, finalY + 29, leftX + boxWidth - 10, finalY + 29); // signature line

  doc.text('Date', leftX + 5, finalY + 36);
  doc.text(':', leftX + 25, finalY + 36);
  doc.line(leftX + 30, finalY + 36, leftX + boxWidth - 10, finalY + 36); // date line

  // Right Box - Signed By
  doc.setDrawColor(200, 210, 230);
  doc.setFillColor(252, 253, 255); // Reset fill color here to prevent black box
  doc.rect(rightX, finalY, boxWidth, boxHeight, 'FD');
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(20, 50, 120);
  doc.text('SIGNED BY', rightX + 5, finalY + 7);
  
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.text('Name', rightX + 5, finalY + 15);
  doc.text(':', rightX + 25, finalY + 15);
  doc.text(signedBy, rightX + 30, finalY + 15);
  
  doc.text('Position', rightX + 5, finalY + 22);
  doc.text(':', rightX + 25, finalY + 22);
  doc.text(signedPosition, rightX + 30, finalY + 22);
  
  doc.text('Signature', rightX + 5, finalY + 29);
  doc.text(':', rightX + 25, finalY + 29);
  doc.setDrawColor(180, 180, 180);
  doc.line(rightX + 30, finalY + 29, rightX + boxWidth - 10, finalY + 29); // signature line

  doc.text('Date', rightX + 5, finalY + 36);
  doc.text(':', rightX + 25, finalY + 36);
  doc.line(rightX + 30, finalY + 36, rightX + boxWidth - 10, finalY + 36); // date line

  doc.save(filename);
};
